#  mamba env create --name nanotei --file nanotei_environment.yaml 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7.5
  - pysam=0.17.0
  - samtools=1.14
  - minimap2=2.22
  - biopython=1.76
  - pandas=0.24.2
