#  mamba env create --name methylartist --file methylartist_environment.yaml 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9.6
  - neovim=0.3.1
  - pynvim=0.4.3
  - jupyter
