#  mamba env create --name ngs_intro --file ngs_intro_environment.yaml 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc=0.11.9
  - cutadapt=3.5
  - bowtie2=2.4.4
  - samtools=1.11
  - bcftools=1.11
