#  mamba env create --name R-4.0.3 --file R-4.0.3_environment.yaml 
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - r-base=4.0.3
  - r-essentials
  - r-dplyr
  - r-plyr
  - r-doparallel
  - r-dofuture
  - r-hmisc
  - r-ggplot2
  - r-ggcorrplot
  - r-plotrix
  - r-ggbeeswarm
  - r-ggthemes
  - r-gridgraphics
  - r-gridextra
  - r-extrafont
  - r-reshape
  - r-glmnet
  - r-psych
  - r-caret
  - r-glm2
  - r-vcd
  - r-car
  - bioconductor-genomicranges
  - bioconductor-segmentseq
  - bioconductor-rtracklayer
  - bioconductor-complexheatmap
  - bioconductor-enrichedheatmap
  - bioconductor-clusterprofiler
  - bioconductor-org.at.tair.db
  - bioconductor-enrichplot
  - bioconductor-dose
