#  mamba env create --name sRNAseq_mapping --file sRNAseq_mapping_environment.yaml 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake=6.0.3
  - pandas=0.24.2
  - bbmap=38.22
  - cutadapt=1.18
  - fastqc=0.11.8
  - multiqc=1.6
  - bowtie=1.2.2
  - samtools=1.9
  - deeptools=3.1.3
  - ucsc-bedgraphtobigwig=377
