#  mamba env create --name variantcalling --file variantcalling_environment.yaml 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake=6.0.3
  - pandas=0.24.2
  - cutadapt=2.10
  - fastqc=0.11.9
  - bowtie2=2.4.2
  - samtools=1.10
  - bcftools=1.10
  - freebayes=1.3.5
